### ISSUE TITLE
Provide a way to bind links after page load

### ISSUE THREAD

**Issue by jorrit** [furkot/trip-planner#2]
Currently `furkot-plan` links are bound on page load. When I add such a button after page load the click handler is not bound. It would be nice to have an API like this:

``` javascript
var furkotApi = furkotTripPlanner();
furkotApi.bind(container);
```

where container is some dynamically added element that is or contains compatible links or forms. I can call this after inserting some piece of html created via Javascript or inserted after an AJAX call.

Basically, the `initButtons(function () {` part should be exposed when this feature is considered desirable.

**Comment by melitele** [comment]
I'd like to mull it over.

Meanwhile you can forgo 'Plan with Furkot' buttons and autodiscovery and [invoke `plan` method of the trip planner widget directly](https://github.com/furkot/trip-planner#activate-widget-programmatically).

Alternatively you can load the `furkot-trip-planner.js` script dynamically after all 'Plan with Furkot' buttons are added to the page.

**Comment by jorrit** [comment]
Is it OK if I propose a PR?

The reason I want to avoid calling the plan method is because I have all the link building code in place and I wish to reuse it. I add buttons multiple times so loading the script multiple times may be suboptimal.

**Comment by melitele** [comment]
Absolutely. PR's are always welcomed.

**Comment by melitele** [comment]
Provided a method to process dynamically added elements - after adding buttons to the page call:

``` javascript
furkotTripPlanner(container);
```

where `container` is a single DOM element that contains newly added buttons. It can be the `document` to process the entire page. Processing newly added buttons attaches event handler. The buttons that were previously processed are ignored.
